name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - run: pnpm install -g vsce
    - run: pnpm install
    - run: vsce package --out macros.vsix
    - uses: actions/upload-artifact@v2
      with:
        path: macros.vsix