name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        version: 18
    - run: npm install -g vsce
    - run: npm install
    - run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
    - run: vsce publish patch --pat ${{ secrets.VSCE_PAT }}
    - run: git push